FROM ubuntu:latest

# Avoid interactive prompts for TZ:
ENV TZ=US/Eastern
ENV DEBIAN_FRONTEND=noninteractive

# Paths used at runtime:
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PYTHONPATH=/opt/src/libyimmo/wsgi/demo

RUN mkdir -p /opt/src/ \
	&& mkdir -p /opt/build/bsat \
	&& mkdir -p /opt/build/yimmo

ADD . /opt/src/libyimmo

RUN apt update \
	&& apt-get install -y \
		git \
		build-essential \
		autotools-dev \
		libtool \
		autoconf \
		automake \
		pkg-config \
		libev-dev \
                uuid-dev \
		libssl-dev \
		python3-dev \
		python3-pip

RUN pip3 install flask

RUN cd /opt/src && git clone https://github.com/andrew-canaday/libbsat
RUN cd /opt/src/libbsat && ./autogen.sh
RUN cd /opt/src/libyimmo && ./autogen.sh

RUN cd /opt/build/bsat \
	&& /opt/src/libbsat/configure \
	&& make \
	&& make check \
	&& make install

RUN cd /opt/build/yimmo \
	&& /opt/src/libyimmo/configure --enable-examples --enable-wsgi \
	&& make \
	&& make check \
	&& make install


ENTRYPOINT ["/usr/local/bin/yimmo-wsgi", "demo_app", "app"]
