name: Configure, Make, and Check
on: [push]
jobs:
  configure_make_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      #------------------------------------
      # Setup:
      #------------------------------------
      - name: Set up base system
        run: |
          sudo apt update
          sudo apt-get -qq install -y \
            libev-dev \
            apache2-utils
          mkdir -p ./build/bsat
          mkdir -p ./build/yimmo


      #------------------------------------
      # Dependencies:
      #------------------------------------
      - name: Checkout libbsat
        uses: actions/checkout@v2
        with:
          repository: 'andrew-canaday/libbsat'
          path: 'libbsat'

      - name: Generate BSAT Configuration
        run: ./autogen.sh
        working-directory: ./libbsat

      - name: Install libbsat
        run: |
          ../../libbsat/configure \
            --enable-silent-rules \
            --silent
          sudo make install
          sudo ldconfig -v || echo "FYI: ldconfig failed"
        working-directory: ./build/bsat


      #--------------------------------------------------------------------
      # Checkout, configure, make, run tests, and make dist for libyimmo:
      #--------------------------------------------------------------------
      - name: Checkout libyimmo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: 'libyimmo'

      - name: Generate Configuration
        run: ./autogen.sh
        working-directory: ./libyimmo

      - name: Configure
        run: |
          ../../libyimmo/configure \
          --enable-maintainer-debug \
          --enable-examples \
          --enable-wsgi \
          --enable-silent-rules \
          CFLAGS=-fdiagnostics-color=always
        working-directory: ./build/yimmo

      - name: Compile
        run: |
          make 2>./yimmo-warnings.txt \
            || cat ./yimmo-warnings.txt
        working-directory: ./build/yimmo

      - name: Warnings
        run: |
          cat ./yimmo-warnings.txt
        working-directory: ./build/yimmo

      - name: Unit Tests
        run: make VERBOSE='true' check
        env:
          # We didn't ldconfig, so just set the path:
          LD_LIBRARY_PATH: /usr/local/lib
        working-directory: ./build/yimmo

      #--------------------------------------------------------------------
      # Check distribution
      #--------------------------------------------------------------------
      - name: Run Distribution Checks
        run: |
          make distcheck || find . -ipath "*test*" -and -iname "*.log" -exec cat '{}' \;
          make dist
        working-directory: ./build/yimmo

