name: Yimmo-WSGI Docker Image
on:
  push:
    branches:
      - main
    tags:
      - 0.*
jobs:
  # TODO: Make reusable workflow:
  docker_build_default_wsgi:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: andrewcanaday/yimmo-wsgi:0-alpha
          file: ./docker/Dockerfile
          target: yimmo-wsgi

